param_dicts = {'dataset': all,
               'n': 2500,
               'lid': None,
               'dim': None,
               'estimator_name': 'mle',
               'bagging_method': None,
               'submethod_0': None,
               'submethod_error': None,
               'k': 10,
               'sr': None,
               'Nbag': None,
               'pre_smooth': None,
               'post_smooth': False,
               't': None}

param_dicts1 = {'dataset_name': all,
                'n': 2500,
                'lid': None,
                'dim': None,
                'estimator_name': 'mle',
                'bagging_method': 'bag',
                'submethod_0': None,
                'submethod_error': None,
                'k': 10,
                'sr': [0.025 + i * 0.025 for i in range(40)],
                'Nbag': 10,
                'pre_smooth': False,
                'post_smooth': False,
                't': None}

param_dicts2 = {'dataset_name': all,
                'n': [250 + i * 250 for i in range(40)],
                'lid': None,
                'dim': None,
                'estimator_name': 'mle',
                'bagging_method': 'bag',
                'submethod_0': None,
                'submethod_error': None,
                'k': 10,
                'sr': 0.3,
                'Nbag': 10,
                'pre_smooth': False,
                'post_smooth': False,
                't': None}

param_dicts3 = {'dataset_name': "uniform",
                'n': 2500,
                'lid': [1 + i for i in range(40)],
                'dim': 40,
                'estimator_name': 'mle',
                'bagging_method': 'bag',
                'submethod_0': None,
                'submethod_error': None,
                'k': 10,
                'sr': 0.3,
                'Nbag': 10,
                'pre_smooth': False,
                'post_smooth': False,
                't': None}

param_dicts_ = {'dataset_name': all,
                'n': 2500,
                'lid': None,
                'dim': None,
                'estimator_name': 'mle',
                'bagging_method': ['bag', 'bagw', 'bagwth'],
                'submethod_0': None,
                'submethod_error': None,
                'k': [5 + i for i in range(40)],
                'sr': 0.3,
                'Nbag': 10,
                'pre_smooth': False,
                'post_smooth': False,
                't': 1}

param_dicts5 = {'dataset_name': all,
                'n': 2500,
                'lid': None,
                'dim': None,
                'estimator_name': 'mle',
                'bagging_method': 'bag',
                'submethod_0': None,
                'submethod_error': None,
                'k': 10,
                'sr': 0.3,
                'Nbag': [5 + i * 5 for i in range(15)],
                'pre_smooth': False,
                'post_smooth': False,
                't': None}

param_dicts6 = {'dataset_name': all,
                'n': 2500,
                'lid': None,
                'dim': None,
                'estimator_name': 'mle',
                'bagging_method': [None, 'bag', 'bagw', 'bagwth', 'bagbag'],
                'submethod_0': '0',
                'submethod_error': 'log_diff',
                'k': 10,
                'sr': 0.3,
                'Nbag': 10,
                'pre_smooth': False,
                'post_smooth': False,
                't': 1}